### ISSUE TITLE
Build Scrapers

### ISSUE THREAD

**Issue by SheaSmith** [SheaSmith/COSC345-Project#1]
Build the scrapers for different shops.

**Tasks**
- [x] Build Shopify scraper
- [x] Build WooCommerce scraper
- [x] Build Countdown scraper
- [x] FreshChoice scraper
- [x] New World/Pak'nSave scraper
- [x] Warehouse scraper
- [x] Special scrapers for individual shops (if time)
- [x] Write tests for scrapers
- [x] Document scrapers
- [x] Build generic infrastructure
