### ISSUE TITLE
Basic infrastructure

### ISSUE THREAD

**Issue by SheaSmith** [SheaSmith/COSC345-Project#4]
Build out the basic app infrastructure

**Tasks**
- [x] Create modules for the app, shared stuff, and the scraper.
- [x] Add any dependencies needed for each module
- [x] Push to Github
